### PR TITLE
chore(timeout): parameterize pollTimeout 

### PR DESCRIPTION
**Pull request by contacthari21**
Fixes Issue #216

### CODE REVIEW

**Comment by Crim** [comment]
Is there a way to pass this value thru from the UI when defining a cluster or topic?

**Comment by contacthari21** [comment]
> 

Isn't this more related to Consumer configuration and not specific to a cluster/topic configuration?

**Comment by Crim** [comment]
> > 
> 
> Isn't this more related to Consumer configuration and not specific to a cluster/topic configuration?

I think you're correct, but there still needs to be some way to define what that value should be, either via a config property, or via the UI (presumably tied to the cluster definition?, but maybe somewhere else, unsure)

**Comment by contacthari21** [comment]
> > > 
> > 
> > 
> > Isn't this more related to Consumer configuration and not specific to a cluster/topic configuration?
> 
> I think you're correct, but there still needs to be some way to define what that value should be, either via a config property, or via the UI (presumably tied to the cluster definition?, but maybe somewhere else, unsure)



> config



> > > 
> > 
> > 
> > Isn't this more related to Consumer configuration and not specific to a cluster/topic configuration?
> 
> I think you're correct, but there still needs to be some way to allow a user to define what that value should be, either via a config property, or via the UI (presumably tied to the cluster definition?, but maybe somewhere else, unsure)

Ya, passing this value from UI would be another issue to be worked on if I think off.  But what I could do is update the View pojo with getter and setters for pollTimeout and then have it passed as part of WebKafkaConsumerFactory's  createClientConfig in this block below which will take care of the API part .. Does it sound fine ?
       // Build the client config.
        final ClientConfig.Builder clientConfigBuilder = ClientConfig.newBuilder()
            .withTopicConfig(topicConfig)
            .withConsumerId(consumerId)
            .withPartitions(view.getPartitionsAsSet())
            .withMaxResultsPerPartition(view.getResultsPerPartition());

**Comment by contacthari21** [comment]
@Crim Should I update the View table and the Factory and open a PR. I am unable to start up the docker image on localhost in my local, will you be able to run through it after I send in this PR to make sure it is working BAU?

**Pull request merged**
