### PR TITLE
pollTimeout : Set pollTimeout during client creation

### PR DESCRIPTION
**Pull request by contacthari21**
Extending the Fix for #216

### CODE REVIEW

**Comment by contacthari21** [comment]
@Crim are the test failures due to DB not having the new column for pollTimeout ?

**Comment by Crim** [comment]
Yea, I think you'd need to create a migration like are defined here: https://github.com/SourceLabOrg/kafka-webview/tree/master/kafka-webview-ui/src/main/resources/schema/migration/h2

**Comment by contacthari21** [comment]
> Yea, I think you'd need to create a migration like are defined here: https://github.com/SourceLabOrg/kafka-webview/tree/master/kafka-webview-ui/src/main/resources/schema/migration/h2

Thanks @Crim . Sent in the update view table sql and I see tests are successful now, please review

**Comment by Crim** [comment]
At first glance this seems good. I'll try to spend some time today to go thru it more closely and get it merged in, thanks!

**Pull request merged**
